### ISSUE TITLE
Add Keyword Fails when starting with numeric value.

### ISSUE THREAD

**Issue by kilakewe** [serphacker/serposcope#112]
When adding a keyword that starts with a numric value, it says Searches added but in the log shows an error.

The keyword does not upload at all.

This installation uses MYSQL.

```
[2016-05-18 16:43:39,999] [qtp1789550256-11] ERROR c.s.s.d.AbstractDB - SQL error
com.querydsl.core.QueryException: Caught SQLException for insert into `GOOGLE_SEARCH` (`KEYWORD`, `TLD`, `DATACENTER`, `DEVICE`, `LOCAL`, `CUSTOM_PARAMETERS`)
values (?, ?, ?, ?, ?, ?)
	at com.querydsl.sql.DefaultSQLExceptionTranslator.translate(DefaultSQLExceptionTranslator.java:50) ~[serposcope.jar:na]
	at com.querydsl.sql.Configuration.translate(Configuration.java:453) ~[serposcope.jar:na]
	at com.querydsl.sql.dml.SQLInsertClause.executeWithKeys(SQLInsertClause.java:364) ~[serposcope.jar:na]
	at com.querydsl.sql.dml.SQLInsertClause.executeWithKey(SQLInsertClause.java:172) ~[serposcope.jar:na]
	at com.querydsl.sql.dml.SQLInsertClause.executeWithKey(SQLInsertClause.java:153) ~[serposcope.jar:na]
	at com.serphacker.serposcope.db.google.GoogleSearchDB.insert(GoogleSearchDB.java:50) ~[serposcope.jar:na]
	at serposcope.controllers.google.GoogleGroupController.addSearch(GoogleGroupController.java:189) [serposcope.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_91]
	at ninja.params.ControllerMethodInvoker.invoke(ControllerMethodInvoker.java:57) [serposcope.jar:na]
	at ninja.FilterChainEnd.next(FilterChainEnd.java:49) [serposcope.jar:na]
	at serposcope.filters.AdminFilter.filter(AdminFilter.java:39) [serposcope.jar:na]
	at ninja.FilterChainImpl.next(FilterChainImpl.java:35) [serposcope.jar:na]
	at serposcope.filters.XSRFFilter.filter(XSRFFilter.java:35) [serposcope.jar:na]
	at ninja.FilterChainImpl.next(FilterChainImpl.java:35) [serposcope.jar:na]
	at serposcope.filters.GoogleGroupFilter.filter(GoogleGroupFilter.java:71) [serposcope.jar:na]
	at ninja.FilterChainImpl.next(FilterChainImpl.java:35) [serposcope.jar:na]
	at serposcope.filters.CanReadFilter.filter(CanReadFilter.java:52) [serposcope.jar:na]
	at ninja.FilterChainImpl.next(FilterChainImpl.java:35) [serposcope.jar:na]
	at serposcope.filters.AuthFilter.filter(AuthFilter.java:40) [serposcope.jar:na]
	at ninja.FilterChainImpl.next(FilterChainImpl.java:35) [serposcope.jar:na]
	at serposcope.filters.BaseFilter.filter(BaseFilter.java:61) [serposcope.jar:na]
	at ninja.FilterChainImpl.next(FilterChainImpl.java:35) [serposcope.jar:na]
	at ninja.NinjaDefault.onRouteRequest(NinjaDefault.java:102) [serposcope.jar:na]
	at ninja.servlet.NinjaServletDispatcher.service(NinjaServletDispatcher.java:86) [serposcope.jar:na]
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:287) [serposcope.jar:na]
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:277) [serposcope.jar:na]
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:182) [serposcope.jar:na]
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91) [serposcope.jar:na]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85) [serposcope.jar:na]
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:119) [serposcope.jar:na]
	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133) [serposcope.jar:na]
	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130) [serposcope.jar:na]
	at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203) [serposcope.jar:na]
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130) [serposcope.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [serposcope.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [serposcope.jar:na]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [serposcope.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [serposcope.jar:na]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [serposcope.jar:na]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [serposcope.jar:na]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [serposcope.jar:na]
	at org.eclipse.jetty.server.Server.handle(Server.java:497) [serposcope.jar:na]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [serposcope.jar:na]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [serposcope.jar:na]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [serposcope.jar:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [serposcope.jar:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [serposcope.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
Caused by: java.sql.SQLException: Incorrect string value: '\xEF\xBB\xBF200...' for column 'keyword' at row 1
	at org.mariadb.jdbc.internal.SQLExceptionMapper.get(SQLExceptionMapper.java:149) ~[serposcope.jar:na]
	at org.mariadb.jdbc.internal.SQLExceptionMapper.throwException(SQLExceptionMapper.java:106) ~[serposcope.jar:na]
	at org.mariadb.jdbc.MySQLStatement.executeQueryEpilog(MySQLStatement.java:252) ~[serposcope.jar:na]
	at org.mariadb.jdbc.MySQLStatement.execute(MySQLStatement.java:278) ~[serposcope.jar:na]
	at org.mariadb.jdbc.MySQLStatement.executeUpdate(MySQLStatement.java:348) ~[serposcope.jar:na]
	at org.mariadb.jdbc.MySQLPreparedStatement.executeUpdate(MySQLPreparedStatement.java:143) ~[serposcope.jar:na]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[serposcope.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[serposcope.jar:na]
	at com.querydsl.sql.dml.SQLInsertClause.executeWithKeys(SQLInsertClause.java:335) ~[serposcope.jar:na]
	... 48 common frames omitted
Caused by: org.mariadb.jdbc.internal.common.QueryException: Incorrect string value: '\xEF\xBB\xBF200...' for column 'keyword' at row 1
	at org.mariadb.jdbc.internal.mysql.MySQLProtocol.getResult(MySQLProtocol.java:969) ~[serposcope.jar:na]
	at org.mariadb.jdbc.internal.mysql.MySQLProtocol.executeQuery(MySQLProtocol.java:1021) ~[serposcope.jar:na]
	at org.mariadb.jdbc.internal.mysql.MySQLProtocol.executeQuery(MySQLProtocol.java:1003) ~[serposcope.jar:na]
	at org.mariadb.jdbc.MySQLStatement.execute(MySQLStatement.java:271) ~[serposcope.jar:na]
	... 53 common frames omitted
```

**Comment by kilakewe** [comment]
MYSQL says it's due to an incorrect string value:

```
ERROR 1366: 1366: Incorrect string value: '\xEF\xBB\xBF200...' for column 'keyword' at row 1
SQL Statement:
UPDATE `SEO`.`GOOGLE_SEARCH` SET `keyword`='﻿2000 chrysler voyager parts' WHERE `id`='36'
```

Related find:
http://stackoverflow.com/questions/1168036/how-to-fix-incorrect-string-value-errors

**Comment by serphacker** [comment]
It must be an encodage issue, maybe charset is not correctly set to utf8 by serposcope or the database is not created with utf8 charset. I'll fix this later. In the meantime you may be able to fix this by settings your database charset to utf8
