### ISSUE TITLE
NinjaDefault - Emitting bad request 500 in 2.5.1

### ISSUE THREAD

**Issue by rontran** [serphacker/serposcope#127]
After upgrading to 2.5.1, I am getting:

```
ERROR n.NinjaDefault - Emitting bad request 500. Something really wrong when calling route: /admin/logs/view (class: class serposcope.controllers.admin.LogController method: public ninja.Result serposcope.controllers.admin.LogController.viewLog(ninja.Context,java.lang.String,java.lang.String))
java.lang.NullPointerException: null
	at java.lang.String.replace(Unknown Source) ~[na:1.8.0_91]
	at serposcope.controllers.admin.LogController.lambda$null$0(LogController.java:109) ~[serposcope.jar:na]
	at java.util.Iterator.forEachRemaining(Unknown Source) ~[na:1.8.0_91]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[na:1.8.0_91]
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[na:1.8.0_91]
	at serposcope.controllers.admin.LogController.lambda$viewLog$1(LogController.java:107) ~[serposcope.jar:na]
	at ninja.utils.ResultHandler.handleRenderable(ResultHandler.java:87) ~[serposcope.jar:na]
	at ninja.utils.ResultHandler.handleResult(ResultHandler.java:60) ~[serposcope.jar:na]
	at ninja.NinjaDefault.onRouteRequest(NinjaDefault.java:104) ~[serposcope.jar:na]
	at ninja.servlet.NinjaServletDispatcher.service(NinjaServletDispatcher.java:86) [serposcope.jar:na]
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:287) [serposcope.jar:na]
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:277) [serposcope.jar:na]
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:182) [serposcope.jar:na]
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91) [serposcope.jar:na]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85) [serposcope.jar:na]
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:119) [serposcope.jar:na]
	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133) [serposcope.jar:na]
	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130) [serposcope.jar:na]
	at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203) [serposcope.jar:na]
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130) [serposcope.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [serposcope.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [serposcope.jar:na]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [serposcope.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [serposcope.jar:na]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [serposcope.jar:na]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [serposcope.jar:na]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [serposcope.jar:na]
	at org.eclipse.jetty.server.Server.handle(Server.java:497) [serposcope.jar:na]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [serposcope.jar:na]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [serposcope.jar:na]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [serposcope.jar:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [serposcope.jar:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [serposcope.jar:na]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_91]
```

**Comment by serphacker** [comment]
do you still get the error after restarting serposcope ?

**Comment by serphacker** [comment]
fixed on next release

**Comment by rontran** [comment]
It just went  away from weeks of error.
