### ISSUE TITLE
Exception on AssetsController 

### ISSUE THREAD

**Issue by loran750** [serphacker/serposcope#149]
Hello

Here is a defect which occured today : 

[2017-01-27 02:40:52,319] [google-0] INFO  c.s.s.s.g.s.GoogleScraper - GOT status=[403] exception=[none]
[2017-01-27 02:40:52,319] [google-0] WARN  c.s.s.t.g.GoogleTaskRunnable - scrap failed for xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx because of ERROR_NETWORK
[2017-01-27 02:40:52,319] [google-0] WARN  c.s.s.t.g.GoogleTaskRunnable - no more proxy, stopping the thread
[2017-01-27 02:40:52,319] [google-0] INFO  c.s.s.t.g.GoogleTaskRunnable - google thread stopped
[2017-01-27 02:40:54,512] [Thread-114] WARN  c.s.s.t.g.GoogleTask - 1 proxies failed during the task
[2017-01-27 02:40:54,512] [Thread-114] WARN  c.s.s.t.g.GoogleTask - 116 searches have not been checked
[2017-01-27 02:40:54,518] [Thread-114] INFO  c.s.s.t.AbstractTask - task done for module GOOGLE
[2017-01-27 02:43:50,876] [pool-1-thread-1] INFO  s.s.Scheduler - last version 2.6.0 | current version 2.6.0
[2017-01-27 08:43:51,107] [pool-1-thread-1] INFO  s.s.Scheduler - last version 2.6.0 | current version 2.6.0
[2017-01-27 12:04:39,166] [qtp1789550256-39466] ERROR n.AssetsController - error streaming file
org.eclipse.jetty.io.EofException: null
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:192) ~[serposcope.jar:na]
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:408) ~[serposcope.jar:na]
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:302) ~[serposcope.jar:na]
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:129) ~[serposcope.jar:na]
	at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:684) ~[serposcope.jar:na]
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:246) ~[serposcope.jar:na]
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:208) ~[serposcope.jar:na]
	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:480) [serposcope.jar:na]
	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:768) [serposcope.jar:na]
	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:801) [serposcope.jar:na]
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:142) ~[serposcope.jar:na]
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:135) ~[serposcope.jar:na]
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:350) ~[serposcope.jar:na]
	at com.google.common.io.ByteStreams.copy(ByteStreams.java:74) ~[serposcope.jar:na]
	at ninja.AssetsController.streamOutUrlEntity(AssetsController.java:155) [serposcope.jar:na]
	at ninja.AssetsController.access$200(AssetsController.java:49) [serposcope.jar:na]
	at ninja.AssetsController$1.render(AssetsController.java:99) [serposcope.jar:na]
	at ninja.utils.ResultHandler.handleRenderable(ResultHandler.java:87) [serposcope.jar:na]
	at ninja.utils.ResultHandler.handleResult(ResultHandler.java:60) [serposcope.jar:na]
	at ninja.NinjaDefault.onRouteRequest(NinjaDefault.java:104) [serposcope.jar:na]
	at ninja.servlet.NinjaServletDispatcher.service(NinjaServletDispatcher.java:86) [serposcope.jar:na]
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:287) [serposcope.jar:na]
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:277) [serposcope.jar:na]
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:182) [serposcope.jar:na]
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91) [serposcope.jar:na]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85) [serposcope.jar:na]
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:119) [serposcope.jar:na]
	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133) [serposcope.jar:na]
	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130) [serposcope.jar:na]
	at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203) [serposcope.jar:na]
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130) [serposcope.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [serposcope.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [serposcope.jar:na]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [serposcope.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [serposcope.jar:na]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [serposcope.jar:na]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [serposcope.jar:na]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [serposcope.jar:na]
	at org.eclipse.jetty.server.Server.handle(Server.java:497) [serposcope.jar:na]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [serposcope.jar:na]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [serposcope.jar:na]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [serposcope.jar:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [serposcope.jar:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [serposcope.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_77]
Caused by: java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.writev0(Native Method) ~[na:1.8.0_77]
	at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51) ~[na:1.8.0_77]
	at sun.nio.ch.IOUtil.write(IOUtil.java:148) ~[na:1.8.0_77]
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:504) ~[na:1.8.0_77]
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:172) ~[serposcope.jar:na]
	... 44 common frames omitted

Do you need more info ?

regards

**Comment by serphacker** [comment]
Hi, minor issue, not related to serposcope itself. Can be due to : 

_ Network error between your browser and serposcope
_ Network error between a reverse proxy (if any) and serposcope embbed web server
_ File system issue...
