### ISSUE TITLE
ERROR n.NinjaDefault - in Log file

### ISSUE THREAD

**Issue by Sorasma** [serphacker/serposcope#65]
I get the following error in log file, can you tell me what it is:

----------------------------
[2016-01-17 09:24:01,289] [qtp11165360-14] ERROR n.NinjaDefault - Emitting bad request 500. Something really wrong when calling route: /admin/logs/view (class: class serposcope.controllers.admin.LogController method: public ninja.Result serposcope.controllers.admin.LogController.viewLog(ninja.Context,java.lang.String,java.lang.String))
java.lang.NullPointerException: null
	at serposcope.controllers.admin.LogController.lambda$getSortedMapByReverseLength$2(LogController.java:178) ~[serposcope.jar:na]
	at java.util.TreeMap.compare(TreeMap.java:1291) ~[na:1.8.0_66]
	at java.util.TreeMap.put(TreeMap.java:538) ~[na:1.8.0_66]
	at java.util.AbstractMap.putAll(AbstractMap.java:281) ~[na:1.8.0_66]
	at java.util.TreeMap.putAll(TreeMap.java:327) ~[na:1.8.0_66]
	at serposcope.controllers.admin.LogController.getSortedMapByReverseLength(LogController.java:184) ~[serposcope.jar:na]
	at serposcope.controllers.admin.LogController.getObfuscateMap(LogController.java:173) ~[serposcope.jar:na]
	at serposcope.controllers.admin.LogController.viewLog(LogController.java:89) ~[serposcope.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_66]
	at ninja.params.ControllerMethodInvoker.invoke(ControllerMethodInvoker.java:57) ~[serposcope.jar:na]
	at ninja.FilterChainEnd.next(FilterChainEnd.java:49) ~[serposcope.jar:na]
	at serposcope.filters.AdminFilter.filter(AdminFilter.java:39) ~[serposcope.jar:na]
	at ninja.FilterChainImpl.next(FilterChainImpl.java:35) ~[serposcope.jar:na]
	at serposcope.filters.BaseFilter.filter(BaseFilter.java:61) ~[serposcope.jar:na]
	at ninja.FilterChainImpl.next(FilterChainImpl.java:35) ~[serposcope.jar:na]
	at ninja.NinjaDefault.onRouteRequest(NinjaDefault.java:102) ~[serposcope.jar:na]
	at ninja.servlet.NinjaServletDispatcher.service(NinjaServletDispatcher.java:86) [serposcope.jar:na]
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:287) [serposcope.jar:na]
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:277) [serposcope.jar:na]
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:182) [serposcope.jar:na]
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91) [serposcope.jar:na]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85) [serposcope.jar:na]
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:119) [serposcope.jar:na]
	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133) [serposcope.jar:na]
	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130) [serposcope.jar:na]
	at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203) [serposcope.jar:na]
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130) [serposcope.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [serposcope.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [serposcope.jar:na]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [serposcope.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [serposcope.jar:na]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [serposcope.jar:na]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [serposcope.jar:na]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [serposcope.jar:na]
	at org.eclipse.jetty.server.Server.handle(Server.java:497) [serposcope.jar:na]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [serposcope.jar:na]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [serposcope.jar:na]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [serposcope.jar:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [serposcope.jar:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [serposcope.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66]

**Comment by serphacker** [comment]
fixed by 0d154852b2f3ca32e7de18372aa202165c29f0bb (will be shipped in v 2.2.0).
