### ISSUE TITLE
cannot start when mysql

### ISSUE THREAD

**Issue by leekung** [serphacker/serposcope#92]
there are no table name "CONFIG" exist in mysql database.
other tables that exists
GOOGLE_RANK, GOOGLE_RANK_BEST, GOOGLE_SEARCH, GOOGLE_SEARCH_GROUP, GOOGLE_SERP, GOOGLE_TARGET, GOOGLE_TARGET_SUMMARY

[2016-03-02 08:47:42,718] [NinjaJetty] ERROR c.s.s.d.AbstractDB - SQL Error
com.querydsl.core.QueryException: Caught SQLSyntaxErrorException for select `CONFIG`.`VALUE`
from `CONFIG` `CONFIG`
where `CONFIG`.`NAME` = ?
limit ?
	at com.querydsl.sql.DefaultSQLExceptionTranslator.translate(DefaultSQLExceptionTranslator.java:50) ~[serposcope-2.3.0.jar:na]
	at com.querydsl.sql.Configuration.translate(Configuration.java:453) ~[serposcope-2.3.0.jar:na]
	at com.querydsl.sql.AbstractSQLQuery.iterateSingle(AbstractSQLQuery.java:396) ~[serposcope-2.3.0.jar:na]
	at com.querydsl.sql.AbstractSQLQuery.iterate(AbstractSQLQuery.java:328) ~[serposcope-2.3.0.jar:na]
	at com.querydsl.sql.ProjectableSQLQuery.fetchOne(ProjectableSQLQuery.java:372) ~[serposcope-2.3.0.jar:na]
	at com.serphacker.serposcope.db.base.ConfigDB.get(ConfigDB.java:75) [serposcope-2.3.0.jar:na]
	at com.serphacker.serposcope.db.base.ConfigDB.getInt(ConfigDB.java:94) [serposcope-2.3.0.jar:na]
	at com.serphacker.serposcope.db.base.MigrationDB.migrateIfNeeded(MigrationDB.java:68) [serposcope-2.3.0.jar:na]
	at conf.Ninja.onFrameworkStart(Ninja.java:87) [serposcope-2.3.0.jar:na]
	at ninja.Bootstrap.boot(Bootstrap.java:111) [serposcope-2.3.0.jar:na]
	at ninja.servlet.NinjaServletListener.createNinjaBootstrap(NinjaServletListener.java:131) [serposcope-2.3.0.jar:na]
	at ninja.servlet.NinjaServletListener.getInjector(NinjaServletListener.java:109) [serposcope-2.3.0.jar:na]
	at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:47) [serposcope-2.3.0.jar:na]
	at ninja.servlet.NinjaServletListener.contextInitialized(NinjaServletListener.java:61) [serposcope-2.3.0.jar:na]
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:800) [serposcope-2.3.0.jar:na]
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:444) [serposcope-2.3.0.jar:na]
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:791) [serposcope-2.3.0.jar:na]
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:294) [serposcope-2.3.0.jar:na]
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741) [serposcope-2.3.0.jar:na]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [serposcope-2.3.0.jar:na]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132) [serposcope-2.3.0.jar:na]
	at org.eclipse.jetty.server.Server.start(Server.java:387) [serposcope-2.3.0.jar:na]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114) [serposcope-2.3.0.jar:na]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61) [serposcope-2.3.0.jar:na]
	at org.eclipse.jetty.server.Server.doStart(Server.java:354) [serposcope-2.3.0.jar:na]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [serposcope-2.3.0.jar:na]
	at ninja.standalone.NinjaJetty.doStart(NinjaJetty.java:107) [serposcope-2.3.0.jar:na]
	at ninja.standalone.AbstractStandalone.start(AbstractStandalone.java:166) [serposcope-2.3.0.jar:na]
	at ninja.standalone.AbstractStandalone.run(AbstractStandalone.java:87) [serposcope-2.3.0.jar:na]
	at serposcope.lifecycle.Daemon.start(Daemon.java:19) [serposcope-2.3.0.jar:na]
	at serposcope.lifecycle.Daemon.main(Daemon.java:15) [serposcope-2.3.0.jar:na]

**Comment by leekung** [comment]
Error because of my database collation set to utf8mb4_unicode_ci
I drop it and recreate with utf8_general_ci and it works fine.
